backend:
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow
media_folder: "images/posts" # Media files will be stored in the repo under src/assets/images/posts
public_folder: "/images/posts" # The src attribute for uploaded media will begin with assets/images/posts

collections:
  - name: "distritos" # Used in routes, e.g., /admin/collections/blog
    label: "Distritos" # Used in the UI
    folder: "src/distritos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "perfildistrito", label: "Perfil Distrito" }
      - { name: "perfildemografico", label: "Perfil Demografico (2022)" }
      - { name: "razonvoto", label: "¿Qué se vota en el distrito?" }
      - { name: "historialeleccion", label: "Historial de Elección" }
      - {
          name: "lidereshistoricos",
          label: "Liderzagos históricos (si los hay, 3 memorias)",
          widget: "list",
          max: 3,
          min: 1,
        }
      - { name: "diputadosdistritales", label: "Diputados Distritales" }
      - {
          name: "alcaldemun",
          label: "Alcalde Municipal (con todos los municipios)",
        }
      - {
          name: "partidosganadores",
          label: "Partidos ganadores históricos (si los hay, 3 memorias)",
          widget: "list",
          max: 3,
          min: 1,
        }
      - {
          name: "participacionmujeres",
          label: "Participación histórica de mujeres (3 períodos)",
          widget: "list",
          max: 3,
          min: 1,
        }
      - { label: "FotoDistrito", name: "fotodistrito", widget: "image" }
  - name: "publicaciones" # Used in routes, e.g., /admin/collections/blog
    label: "Publicaciones" # Used in the UI
    folder: "src/publicaciones" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { label: "Image", name: "image", widget: "image" }
      - { name: "description", label: "Description" }
      - { name: "autor", label: "Autor" }
      - { name: "correo", label: "Correo" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { label: "Image", name: "image", widget: "image" }
      - { name: "description", label: "Description" }
      - { name: "autor", label: "Autor" }
      - { name: "correo", label: "Correo" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }
  - name: "eventos" # Used in routes, e.g., /admin/collections/blog
    label: "Eventos" # Used in the UI
    folder: "src/eventos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { label: "Image", name: "image", widget: "image" }
      - { name: "description", label: "Description" }
      - { name: "autor", label: "Autor" }
      - { name: "correo", label: "Correo" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }
  - name: "podcast" # Used in routes, e.g., /admin/collections/podcast
    label: "Podcast" # Used in the UI
    folder: "src/podcasts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { name: "description", label: "Description" }
      - { name: "link", label: "Enlace de podcast" }
      - { name: "date", label: "Date", widget: "datetime" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display podcast in home's highlights",
        }

show_preview_links: true
