backend:
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow
media_folder: "images/posts" # Media files will be stored in the repo under src/assets/images/posts
public_folder: "/images/posts" # The src attribute for uploaded media will begin with assets/images/posts

collections:
  - name: "distritos" # Used in routes, e.g., /admin/collections/blog
    label: "Distritos" # Used in the UI
    folder: "src/distritos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "nombre", label: "Nombre Distrito" }
      - { name: "perfildistrito", label: "Perfil Distrito", widget: "markdown" }
      - {
          name: "perfildemografico",
          label: "Perfil Demografico (2022)",
          widget: "markdown",
        }
      - {
          name: "razonvoto",
          label: "¿Qué se vota en el distrito?",
          widget: "markdown",
        }
      - {
          name: "historialeleccion",
          label: "Historial de Elección",
          widget: "markdown",
        }
      - {
          name: "lidereshistoricos",
          label: "Liderzagos históricos (si los hay, 3 memorias)",
          widget: "markdown",
        }
      - {
          name: "diputadosdistritales",
          label: "Diputados Distritales",
          widget: "markdown",
        }
      - {
          name: "alcaldemun",
          label: "Alcalde Municipal (con todos los municipios)",
          widget: "markdown",
        }
      - {
          name: "partidosganadores",
          label: "Partidos ganadores históricos (si los hay, 3 memorias)",
          widget: "markdown",
        }
      - {
          name: "participacionmujeres",
          label: "Participación histórica de mujeres (3 períodos)",
          widget: "markdown",
        }
      - { label: "FotoDistrito", name: "fotodistrito", widget: "image" }
  - name: "elecciones" # Used in routes, e.g., /admin/collections/blog
    label: "Elecciones" # Used in the UI
    folder: "src/elecciones" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "queelige", label: "¿Qué se elige?", widget: "markdown" }
      - {
          name: "participantes",
          label: "¿Quienes participan?",
          widget: "markdown",
        }
      - { name: "reglas", label: "Reglas de juego", widget: "markdown" }
      - {
          name: "info",
          label: "Información para el día de la elección",
          widget: "markdown",
        }
      - { name: "caminovoto", label: "Camino del voto", widget: "markdown" }
      - {
          name: "links a sitios oficiales",
          label: "Links a sitios oficiales y de interés",
          widget: "markdown",
        }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - { label: "Mapa", name: "mapa", widget: "image" }
  - name: "publicaciones" # Used in routes, e.g., /admin/collections/blog
    label: "Publicaciones" # Used in the UI
    folder: "src/publicaciones" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { label: "Image", name: "image", widget: "image" }
      - { name: "description", label: "Description" }
      - { name: "autor", label: "Autor" }
      - { name: "correo", label: "Correo" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { label: "Image", name: "image", widget: "image" }
      - { name: "description", label: "Description" }
      - { name: "autor", label: "Autor" }
      - { name: "correo", label: "Correo" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }
  - name: "eventos" # Used in routes, e.g., /admin/collections/blog
    label: "Eventos" # Used in the UI
    folder: "src/eventos" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { label: "Image", name: "image", widget: "image" }
      - { name: "description", label: "Description" }
      - { name: "autor", label: "Autor" }
      - { name: "correo", label: "Correo" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display posts in home's highlights",
        }
  - name: "podcast" # Used in routes, e.g., /admin/collections/podcast
    label: "Podcast" # Used in the UI
    folder: "src/podcasts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { name: "description", label: "Description" }
      - { name: "link", label: "Enlace de podcast" }
      - { name: "date", label: "Date", widget: "datetime" }
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
          hint: "Display podcast in home's highlights",
        }

show_preview_links: true
